# Generated by Django 5.1.4 on 2024-12-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_aksiya_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aksiya',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
