# Generated by Django 5.1.4 on 2024-12-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100)),
                ('compacity', models.CharField(max_length=100)),
                ('wheel_formula', models.CharField(max_length=10)),
                ('dimensions', models.CharField(max_length=100)),
                ('working_volume', models.CharField(max_length=10)),
                ('wheelbase', models.CharField(max_length=100)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.characteristic')),
            ],
        ),
    ]
