# Generated by Django 5.1.4 on 2024-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_characteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category/'),
            preserve_default=False,
        ),
    ]
