# Generated by Django 5.1.4 on 2024-12-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='compacity_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='compacity_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='compacity_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='dimensions_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='dimensions_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='dimensions_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='fuel_type_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fueltype'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='fuel_type_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fueltype'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='fuel_type_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.fueltype'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='weight_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='weight_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='weight_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheel_formula_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheel_formula_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheel_formula_uz',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheelbase_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheelbase_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='wheelbase_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='working_volume_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='working_volume_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='working_volume_uz',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
