# Generated by Django 4.2 on 2024-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_characteristic_compacity_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
